daemon              off;
listen              1935;
max_connections     100;
srs_log_tank        console;

exporter {
    enabled on;
    listen  8000;
    label   srs-cluster-origin;
    tag     srs-cluster-origin;
}

http_api {
    enabled on;
    listen  1985;
}

vhost __defaultVhost__ {
    publish {
        firstpkt_timeout    20000;
        normal_timeout      20000;
    }

    dvr {
        enabled                         on;
        dvr_apply                       all;
        dvr_plan                        segment;
        dvr_path                        ./objs/records/[stream]-[timestamp].flv;
        dvr_duration                    60;
        # Discard files at or below this size before the final rename and do not trigger on_dvr.
        # Overwrite by env SRS_VHOST_DVR_DVR_MIN_FILE_SIZE. Zero disables the filter.
        dvr_min_file_size               267;
        dvr_wait_keyframe               on;
        time_jitter                     full;
    }

    http_hooks {
        enabled         on;
        on_publish      http://localhost:9000/internal/control/stream/connect;
        on_unpublish    http://localhost:9000/internal/control/stream/disconnect;
        on_dvr          http://localhost:9009/record/done;
    }   
}
